### ISSUE TITLE
Clarify if you need to deny all fault bases or just some?

### ISSUE THREAD

**Issue by gbls-issues** [GBLS/docassemble-MAEvictionDefense#134]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `fault defenses`
What was confusing | On Page id: fault defenses

What if I deny one fault, but not the other?
Other information | 
Variable being sought | `fault.did_not_occur`

**Comment by michaelhofrichter** [comment]
For example -- `If you do not agree with the landlord’s allegation of chronic late payment of rent and clutter or hoarding, you may have a defense. Select all that apply below.` What if they agree about the clutter, but not the chronic late payments? Or vice versa?

**Comment by nonprofittechy** [comment]
This might be fixable with just a little explanation to answer "yes" if you deny at least one fault basis.
