### ISSUE TITLE
RAFT delay may not be getting into answer

### ISSUE THREAD

**Issue by plocket** [GBLS/docassemble-MAEvictionDefense#155]
For RAFT being delayed, I assume the question to which that’s referring is on the ‘covid_cdc_moratorium’ page - the variable delay_in_raft. If so, I’m not seeing RAFT mentioned in the answer.

Video of slow automated test and its documents: https://drive.google.com/drive/folders/15BQMhFxXcc3TwjWN9qiqE7VBX7sa7I5q?usp=sharing

**Comment by nonprofittechy** [comment]
This is the paragraph that is inserted in the answer if someone answers "yes" to: `I have asked for help from RAFT or another rental help program and my rent is late because RAFT has not paid my rent yet.`


```
The Court Should Continue this Case for Payment by Government Agency

12.	The court should postpone this case for at least seven days (or such longer time as needed for the tender by the government agency) and, if the rent and court costs are then tendered/offered, the landlord’s claims for rent and possession must be dismissed.  G.L. c. 186, §11 and 12.
```

**Comment by plocket** [comment]
It looks like the test doe check off that box and I don't see the above text in the Answer.pdf. Did you see the video and confirm the PDF?

**Comment by nonprofittechy** [comment]
The correct text is in the pdf.
