### ISSUE TITLE
Tests not including proper files

### ISSUE THREAD

**Issue by nonprofittechy** [GBLS/docassemble-MAEvictionDefense#157]
![error-Userscourtdatehaspassed](https://user-images.githubusercontent.com/7645641/100481848-7edb7680-30c3-11eb-8c52-3aa4084256bf.jpg)

**Comment by plocket** [comment]
From what I can see of the test, it's probably a race condition - the rest of the tests passed. If we keep actions enabled I can re-run the test a couple of times and see if something more revealing happens.

I've seen it a few times before and it's resolved on re-runs. It may be that the server hasn't completely finished loading even after `test.yml` can be found. I'll talk to the team and see if we can think of some way to make those race conditions less likely.

**Comment by plocket** [comment]
Working on adding polling to that functionality. I think this method shouldn't slow things down too much.

**Comment by plocket** [comment]
As seen above, the PR has been made.
