### ISSUE TITLE
Should lack of defaults cause test failure?

### ISSUE THREAD

**Issue by plocket** [GBLS/docassemble-MAEvictionDefense#166]
When some languages are missing default answers, should that prompt test failure, or do we just need to adjust the tests to complete all required fields?

**Comment by nonprofittechy** [comment]
It's not really an important bug, and it takes a lot of work to track down in all the translation files. we'll also need to re-fix that in all of the translation files when we get updated ones in a few weeks. the problem is the translation file offers all mako text for translation, even defaults.

**Comment by plocket** [comment]
In that case, I'll try to write all tests in the future so that they deliberately fill in the answers that are the default answers. It'll take a little longer, but it'll save on those errors.
